/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chapter {
  'title' : string,
  'mcqs' : Array<MCQ>,
  'notes' : string,
  'number' : bigint,
}
export interface ForumPost {
  'title' : string,
  'subject' : string,
  'body' : string,
  'author' : Principal,
  'timestamp' : Time,
  'replies' : Array<ForumReply>,
  'postId' : string,
}
export interface ForumReply {
  'body' : string,
  'author' : Principal,
  'timestamp' : Time,
  'replyId' : string,
  'postId' : string,
}
export interface MCQ {
  'question' : string,
  'correctIndex' : bigint,
  'options' : Array<string>,
}
export interface QuizAttempt {
  'attemptId' : string,
  'subject' : string,
  'score' : bigint,
  'totalQuestions' : bigint,
  'timestamp' : Time,
  'chapter' : string,
}
export interface SamplePaper {
  'id' : string,
  'title' : string,
  'subject' : string,
  'year' : bigint,
  'description' : string,
}
export interface Subject {
  'id' : string,
  'title' : string,
  'chapters' : Array<Chapter>,
}
export type Time = bigint;
export interface UserProfile { 'bio' : [] | [string], 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStudyTask {
  'title' : string,
  'subject' : string,
  'completed' : boolean,
  'taskId' : string,
  'timestamp' : Time,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addForumPost' : ActorMethod<[string, string, string], string>,
  'addForumReply' : ActorMethod<[string, string], string>,
  'addStudyTask' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllForumPosts' : ActorMethod<[], Array<ForumPost>>,
  'getAllSamplePapers' : ActorMethod<[], Array<SamplePaper>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChapter' : ActorMethod<[string, bigint], [] | [Chapter]>,
  'getChapterMCQs' : ActorMethod<[string, bigint], [] | [Array<MCQ>]>,
  'getForumPostById' : ActorMethod<[string], [] | [ForumPost]>,
  'getQuizAttemptsForCaller' : ActorMethod<[], Array<QuizAttempt>>,
  'getSamplePaperById' : ActorMethod<[string], [] | [SamplePaper]>,
  'getSamplePapersBySubject' : ActorMethod<[string], Array<SamplePaper>>,
  'getSubjectById' : ActorMethod<[string], [] | [Subject]>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'getTasksForCaller' : ActorMethod<[], Array<UserStudyTask>>,
  'getUserCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVersion' : ActorMethod<[], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markTaskCompleted' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveQuizAttempt' : ActorMethod<[string, string, bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];