/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ForumReply = IDL.Record({
  'body' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'replyId' : IDL.Text,
  'postId' : IDL.Text,
});
export const ForumPost = IDL.Record({
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'body' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'replies' : IDL.Vec(ForumReply),
  'postId' : IDL.Text,
});
export const SamplePaper = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});
export const MCQ = IDL.Record({
  'question' : IDL.Text,
  'correctIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const Chapter = IDL.Record({
  'title' : IDL.Text,
  'mcqs' : IDL.Vec(MCQ),
  'notes' : IDL.Text,
  'number' : IDL.Nat,
});
export const QuizAttempt = IDL.Record({
  'attemptId' : IDL.Text,
  'subject' : IDL.Text,
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'timestamp' : Time,
  'chapter' : IDL.Text,
});
export const Subject = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'chapters' : IDL.Vec(Chapter),
});
export const UserStudyTask = IDL.Record({
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'completed' : IDL.Bool,
  'taskId' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addForumPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'addForumReply' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'addStudyTask' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllForumPosts' : IDL.Func([], [IDL.Vec(ForumPost)], ['query']),
  'getAllSamplePapers' : IDL.Func([], [IDL.Vec(SamplePaper)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChapter' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Opt(Chapter)], ['query']),
  'getChapterMCQs' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Opt(IDL.Vec(MCQ))],
      ['query'],
    ),
  'getForumPostById' : IDL.Func([IDL.Text], [IDL.Opt(ForumPost)], ['query']),
  'getQuizAttemptsForCaller' : IDL.Func([], [IDL.Vec(QuizAttempt)], ['query']),
  'getSamplePaperById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SamplePaper)],
      ['query'],
    ),
  'getSamplePapersBySubject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SamplePaper)],
      ['query'],
    ),
  'getSubjectById' : IDL.Func([IDL.Text], [IDL.Opt(Subject)], ['query']),
  'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getTasksForCaller' : IDL.Func([], [IDL.Vec(UserStudyTask)], ['query']),
  'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVersion' : IDL.Func([], [IDL.Text], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markTaskCompleted' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveQuizAttempt' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ForumReply = IDL.Record({
    'body' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'replyId' : IDL.Text,
    'postId' : IDL.Text,
  });
  const ForumPost = IDL.Record({
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'body' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'replies' : IDL.Vec(ForumReply),
    'postId' : IDL.Text,
  });
  const SamplePaper = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
  });
  const MCQ = IDL.Record({
    'question' : IDL.Text,
    'correctIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const Chapter = IDL.Record({
    'title' : IDL.Text,
    'mcqs' : IDL.Vec(MCQ),
    'notes' : IDL.Text,
    'number' : IDL.Nat,
  });
  const QuizAttempt = IDL.Record({
    'attemptId' : IDL.Text,
    'subject' : IDL.Text,
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'timestamp' : Time,
    'chapter' : IDL.Text,
  });
  const Subject = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'chapters' : IDL.Vec(Chapter),
  });
  const UserStudyTask = IDL.Record({
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'completed' : IDL.Bool,
    'taskId' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addForumPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'addForumReply' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'addStudyTask' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllForumPosts' : IDL.Func([], [IDL.Vec(ForumPost)], ['query']),
    'getAllSamplePapers' : IDL.Func([], [IDL.Vec(SamplePaper)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChapter' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Opt(Chapter)], ['query']),
    'getChapterMCQs' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(IDL.Vec(MCQ))],
        ['query'],
      ),
    'getForumPostById' : IDL.Func([IDL.Text], [IDL.Opt(ForumPost)], ['query']),
    'getQuizAttemptsForCaller' : IDL.Func(
        [],
        [IDL.Vec(QuizAttempt)],
        ['query'],
      ),
    'getSamplePaperById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SamplePaper)],
        ['query'],
      ),
    'getSamplePapersBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SamplePaper)],
        ['query'],
      ),
    'getSubjectById' : IDL.Func([IDL.Text], [IDL.Opt(Subject)], ['query']),
    'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getTasksForCaller' : IDL.Func([], [IDL.Vec(UserStudyTask)], ['query']),
    'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVersion' : IDL.Func([], [IDL.Text], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markTaskCompleted' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveQuizAttempt' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };